(() => {
  const config = window.BREAKOUT_CONFIG || {};
  const tr = {
    ru:{
      navFeatures:'Возможности',featuresKicker:'Возможности',featuresTitle:'Нужные инструменты — в одном рабочем пространстве.',featuresIntro:'BreakOut построен из модулей: можно собрать рабочий экран под матч, разбор или подготовку материала и держать рядом только то, что нужно сейчас.',f1t:'Захват матча',f1d:'Подключайте видеосигнал, записывайте матч и работайте с видео прямо внутри проекта.',f2t:'Таймлайн и события',f2d:'Отмечайте игровые события на таймлайне и быстро возвращайтесь к нужному моменту.',f3t:'Программируемые кнопки',f3d:'Создавайте собственные кнопки и горячие клавиши под свою систему кодирования игры.',f4t:'Повтор и просмотр',f4d:'Открывайте нужный эпизод, пересматривайте его и продолжайте работу, не теряя контекст матча.',f5t:'Статистика',f5d:'Сводите отмеченные события в наглядную статистику для разбора после игры.',f6t:'Экспорт',f6d:'Экспортируйте выбранные эпизоды и подготовленные подборки для дальнейшей работы.',w1t:'Соберите экран',w1d:'Выберите модули под текущую работу.',w2t:'Настройте события',w2d:'Подготовьте кнопки, горячие клавиши и временную логику до начала матча.',w3t:'Работайте по ходу матча',w3d:'Отмечайте события, возвращайтесь к эпизодам и следите за таймлайном.',w4t:'Разберите и экспортируйте',w4d:'Используйте статистику и экспорт для подготовки нужного материала.',macTitle:'BreakOut — отдельное приложение для Mac.',macFact2Title:'macOS 12.5+',
      navDemo:'Демо',navBenefits:'Преимущества',navShowcase:'Интерфейс',navPricing:'Тарифы',navSupport:'Поддержка',navPrivacy:'Конфиденциальность',signIn:'Войти',termsShort:'Условия',lightTheme:'Светлая тема',darkTheme:'Тёмная тема',zoomScreenshot:'Увеличить скриншот',closeScreenshot:'Закрыть',
      eyebrow:'Профессиональный спортивный видеоанализ для Mac',heroTitle:'Видеть игру.\nОтмечать главное.\nРазбирать без задержек.',heroLead:'BreakOut объединяет работу с видео, событиями, повтором, статистикой и экспортом в одном настраиваемом рабочем пространстве — для тренеров, аналитиков и спортивных команд.',tryDemo:'Попробовать демо',download:'Скачать для Mac',forMac:'Для Mac',macRequirement:'macOS 12.5 и новее',modulesAvailable:'основных модулей в одном пространстве',realInterface:'Реальный интерфейс BreakOut',
      demoKicker:'Интерактивное демо',demoTitle:'Нажмите кнопку. Событие уже на таймлайне.',demoIntro:'Попробуйте кнопки, растяните метку, откройте повтор и измените размеры модулей. Это интерактивная демонстрация логики BreakOut, а не обработка реального видео.',demoMode:'Демо режима матча',captureActive:'Захват активен',captureModule:'Просмотр видео',buttonsModule:'Программируемые кнопки',timelineModule:'Таймлайн',replayModule:'Повтор',beforeAfterShort:'до / после',startStopShort:'старт / стоп',chance:'Момент +',legendBeforeAfter:'До / после — одна отметка',legendStartStop:'Старт / стоп — повторное нажатие завершает событие',trackChance:'Момент',selectMarker:'Выберите метку на таймлайне',helpClick:'создать / выбрать событие',helpResize:'потянуть край метки',helpMove:'перенести на другую линию',helpContext:'контекстное меню',ctxExport:'Экспортировать…',ctxComposer:'Добавить в Компоузер',ctxShare:'Поделиться видеофрагментом…',ctxDetails:'Открыть карточку события…',ctxStar:'Поставить звёздочку',ctxUnstar:'Убрать звёздочку',ctxDelete:'Удалить',
      workflowKicker:'Один рабочий процесс',workflowTitle:'От события в матче — до готового материала.',workflowIntro:'Основные действия связаны между собой: меньше переключений между разными инструментами, больше внимания самой игре.',wf1:'Матч',wf1d:'Видео находится перед глазами.',wf2:'Отметка',wf2d:'Кнопка создаёт событие на таймлайне.',wf3:'Повтор',wf3d:'Нужный эпизод открывается из метки.',wf4:'Разбор',wf4d:'Статистика и рисование помогают объяснить момент.',wf5:'Экспорт',wf5d:'Выбранный материал готовится для дальнейшей работы.',
      liveKicker:'Для работы в реальном темпе',liveTitle:'Интерфейс не должен отвлекать от игры.',liveIntro:'BreakOut строится вокруг рабочего процесса аналитика: нужные модули рядом, события отмечаются сразу, а после матча уже есть структура для разбора.',b1t:'Оставайтесь в игре',b1d:'Программируемые кнопки и горячие клавиши позволяют отмечать события, не уходя из рабочего экрана.',b1s:'Минимум лишних переключений',b2t:'Вернитесь к моменту за секунды',b2d:'Метка на таймлайне становится точкой входа в повтор и дальнейший разбор эпизода.',b2s:'Событие уже связано со временем матча',b3t:'Соберите пространство под задачу',b3d:'Захват, таймлайн, кнопки, повтор, статистика, экспорт, рисование и несколько ракурсов можно компоновать под свою работу.',b3s:'Модульное рабочее пространство',
      showcaseKicker:'Реальный интерфейс',showcaseTitle:'От подготовки — к разбору после матча.',showcaseIntro:'Реальные экраны BreakOut в том порядке, в котором строится работа.',slide1t:'Подготовка рабочего пространства',slide1d:'Выберите модули, которые нужны для конкретной задачи, и расположите их удобным образом.',slide2t:'Настройка системы кодирования',slide2d:'Создавайте кнопки, назначайте горячие клавиши и задавайте временную логику событий.',slide3t:'Работа во время матча',slide3d:'Захват, таймлайн, программируемые кнопки и повтор собраны в одном рабочем пространстве.',slide4t:'Статистика и экспорт',slide4d:'После матча смотрите статистику по отмеченным событиям и экспортируйте нужный материал.',
      macKicker:'Разработано для Mac',macFact1Title:'Приложение для Mac',macFact1Text:'Нативный рабочий процесс на компьютере.',macFact2Text:'Минимальная версия системы.',macFact3Title:'Модульный интерфейс',macFact3Text:'Размер и состав рабочего пространства подстраиваются под задачу.',directDownload:'Прямая загрузка',directDownloadText:'Распространение вне App Store будет подключено к запуску.',
      pricingKicker:'Тарифы',pricingTitle:'Полный рабочий процесс BreakOut.',pricingIntro:'Оплата пока не подключена. Кнопки уже находятся на своих местах и станут активными после запуска продаж.',sixMonths:'6 месяцев',oneYear:'1 год',comingSoon:'Скоро',priceIncludes:'Доступ к функционалу BreakOut на оплаченный срок.',chooseSix:'Выбрать 6 месяцев',chooseYear:'Выбрать 1 год',
      privacyKicker:'Доверие и конфиденциальность',privacyTitle:'Понятные правила до первой покупки.',privacyText:'На текущем сайте нет рекламных трекеров и обработки данных банковских карт. Перед подключением аккаунтов и оплаты политика будет обновлена под реальную схему работы.',privacyLink:'Политика конфиденциальности →',termsLink:'Условия использования →',ctaEyebrow:'BreakOut для Mac',ctaTitle:'Разбор начинается не после матча. Он начинается в момент события.',contactSupport:'Связаться с поддержкой',
      modalTitle:'Функция пока недоступна',modalBody:'Публичная загрузка, вход и оплата будут подключены позже.',modalDownload:'Публичная загрузка BreakOut пока не открыта.',modalAccount:'Вход в аккаунт BreakOut появится позже.',modalPayment:'Оплата пока не подключена. Никакого списания не произойдёт.',close:'Закрыть',
      demoToastExport:'В приложении здесь открывается экспорт выбранного события.',demoToastComposer:'В приложении событие можно добавить в Компоузер.',demoToastShare:'В приложении здесь открывается системное меню «Поделиться».',demoToastDetails:'В приложении здесь открывается карточка события.',demoToastMove:'Удерживайте ⌘ и перетащите метку вверх или вниз.',
      backHome:'← На главную',supportTitle:'Поддержка',supportIntro:'Помощь по BreakOut для macOS: установка, доступ, работа приложения и вопросы по продукту.',supportEmailTitle:'Поддержка по e-mail',supportEmailCopy:'Для технических вопросов, отзывов о программе и вопросов по доступу.',supportEmailButton:'Написать',supportAccessTitle:'Загрузка и доступ',supportAccessCopy:'Публичная загрузка и вход в аккаунт откроются к коммерческому запуску BreakOut.',supportAccessButton:'Посмотреть тарифы',supportBeforeTitle:'Если возникла техническая проблема',supportBeforeCopy:'Укажите версию BreakOut, версию macOS, что вы делали перед ошибкой и точный текст сообщения. Если проблема видна на экране, приложите скриншот.',supportPaymentsTitle:'Оплата и подписка',supportPaymentsCopy:'После запуска продаж в аккаунте BreakOut можно будет видеть информацию о доступе и подписке.',
      privacyPageTitle:'Политика конфиденциальности',privacyPageIntro:'Как сайт BreakOut обращается с информацией до запуска аккаунтов и оплаты.',version:'Версия: 19 августа 2026',privacyNotice:'На текущем сайте нет форм аккаунта и обработки платежей. Также здесь нет рекламных пикселей и маркетинговой аналитики.',privacy1Title:'1. Информация на текущем сайте',privacy1Copy:'BreakOut не собирает через этот сайт логины и пароли, данные банковских карт, видео матчей или файлы проектов. Если вы пишете в поддержку по e-mail, переданная информация используется для ответа на обращение.',privacy2Title:'2. Аккаунты и доступ',privacy2Copy:'Когда появятся аккаунты пользователей, политика будет обновлена и будет ясно описывать, какие данные нужны и зачем.',privacy3Title:'3. Оплата',privacy3Copy:'Данные банковской карты будет обрабатывать выбранный платёжный провайдер, а не сайт BreakOut.',privacy4Title:'4. Видео и проекты',privacy4Copy:'BreakOut предназначен для профессиональной работы с видео на Mac. Будущие сетевые функции, если они появятся, будут описаны до их включения.',privacy5Title:'5. Контакты',privacy5Copy:'Вопросы о конфиденциальности можно отправить на',
      termsPageTitle:'Условия использования',termsPageIntro:'Основные условия использования сайта BreakOut до начала публичных продаж.',termsNotice:'Сейчас через сайт нельзя совершить покупку. Цены на главной странице являются планируемыми ценами запуска.',terms1Title:'1. Сайт',terms1Copy:'Сайт представляет BreakOut и приложение для Mac. Пока загрузка, вход и покупка не открыты, соответствующие кнопки показывают уведомление о недоступности.',terms2Title:'2. Доступ к программе',terms2Copy:'После начала продаж использование BreakOut будет требовать действующего оплаченного доступа.',terms3Title:'3. Интеллектуальная собственность',terms3Copy:'BreakOut, фирменное оформление, программное обеспечение и оригинальные материалы защищаются применимыми правилами интеллектуальной собственности. Получение копии приложения не даёт права распространять его от своего имени.',terms4Title:'4. Доступ и оплата',terms4Copy:'Срок доступа, продление, отмена, возвраты, налоги и условия оплаты будут ясно показаны до оплаты.',terms5Title:'5. Контакты',terms5Copy:'Вопросы об условиях можно отправить на'
    },
    en:{
      navFeatures:'Features',featuresKicker:'Features',featuresTitle:'The tools you need, in one workspace.',featuresIntro:'BreakOut is built from modules, so you can assemble the screen for a match, review or preparation and keep only the tools you need close at hand.',f1t:'Match capture',f1d:'Connect a video source, record the match and work with video inside the project.',f2t:'Timeline and events',f2d:'Mark game events on the timeline and return to the exact moment quickly.',f3t:'Programmable buttons',f3d:'Create your own buttons and hotkeys around your coding system.',f4t:'Replay and review',f4d:'Open the right episode, review it and continue without losing match context.',f5t:'Statistics',f5d:'Turn coded events into a clear post-game statistical view.',f6t:'Export',f6d:'Export selected episodes and prepared material for the next step.',w1t:'Build the workspace',w1d:'Choose the modules needed for the task.',w2t:'Configure coding',w2d:'Prepare buttons, hotkeys and event timing before the match.',w3t:'Work during the match',w3d:'Mark events, return to episodes and follow the timeline.',w4t:'Review and export',w4d:'Use statistics and export to prepare the material you need.',macTitle:'BreakOut is a dedicated Mac app.',macFact2Title:'macOS 12.5+',
      navDemo:'Demo',navBenefits:'Benefits',navShowcase:'Interface',navPricing:'Pricing',navSupport:'Support',navPrivacy:'Privacy',signIn:'Sign in',termsShort:'Terms',lightTheme:'Light theme',darkTheme:'Dark theme',zoomScreenshot:'Enlarge screenshot',closeScreenshot:'Close',
      eyebrow:'Professional sports video analysis for Mac',heroTitle:'See the game.\nMark what matters.\nReview without delay.',heroLead:'BreakOut brings video, event coding, replay, statistics and export into one configurable Mac workspace for coaches, analysts and sports teams.',tryDemo:'Try the demo',download:'Download for Mac',forMac:'For Mac',macRequirement:'macOS 12.5 or later',modulesAvailable:'core modules in one workspace',realInterface:'Real BreakOut interface',
      demoKicker:'Interactive demo',demoTitle:'Press a button. The event is already on the timeline.',demoIntro:'Try the buttons, resize a marker, open a replay and resize the modules. This is an interactive BreakOut workflow demo, not real video processing.',demoMode:'Match-mode demo',captureActive:'Capture active',captureModule:'Video',buttonsModule:'Programmable buttons',timelineModule:'Timeline',replayModule:'Replay',beforeAfterShort:'before / after',startStopShort:'start / stop',chance:'Chance +',legendBeforeAfter:'Before / after — creates one event',legendStartStop:'Start / stop — press again to finish the event',trackChance:'Chance',selectMarker:'Select a marker on the timeline',helpClick:'create / select an event',helpResize:'drag a marker edge',helpMove:'move to another track',helpContext:'context menu',ctxExport:'Export…',ctxComposer:'Add to Composer',ctxShare:'Share video clip…',ctxDetails:'Open event card…',ctxStar:'Star event',ctxUnstar:'Remove star',ctxDelete:'Delete',
      workflowKicker:'One workflow',workflowTitle:'From an in-game event to prepared material.',workflowIntro:'The core actions connect to each other: less tool switching, more attention on the game.',wf1:'Match',wf1d:'Keep the video in front of you.',wf2:'Mark',wf2d:'A button creates an event on the timeline.',wf3:'Replay',wf3d:'Open the right episode from its marker.',wf4:'Review',wf4d:'Statistics and drawing help explain the moment.',wf5:'Export',wf5d:'Prepare selected material for the next step.',
      liveKicker:'Built for live work',liveTitle:'The interface should not pull you away from the game.',liveIntro:'BreakOut is built around the analyst’s workflow: the needed modules stay close, events are marked immediately, and the match already has structure when review begins.',b1t:'Stay on the game',b1d:'Programmable buttons and hotkeys let you mark events without leaving the working screen.',b1s:'Fewer unnecessary switches',b2t:'Return to a moment in seconds',b2d:'A timeline marker becomes the entry point for replay and further analysis.',b2s:'The event is already tied to match time',b3t:'Build the workspace around the job',b3d:'Capture, timeline, buttons, replay, statistics, export, drawing and multiple angles can be arranged around your workflow.',b3s:'A modular workspace',
      showcaseKicker:'Real interface',showcaseTitle:'From preparation to post-game review.',showcaseIntro:'Real BreakOut screens shown in the order the workflow happens.',slide1t:'Prepare the workspace',slide1d:'Choose the modules needed for the task and arrange them in a useful layout.',slide2t:'Configure the coding system',slide2d:'Create buttons, assign hotkeys and define event timing logic.',slide3t:'Work during the match',slide3d:'Capture, timeline, programmable buttons and replay share one workspace.',slide4t:'Statistics and export',slide4d:'After the match, review coded-event statistics and export the material you need.',
      macKicker:'Designed for Mac',macFact1Title:'Mac application',macFact1Text:'A native desktop workflow.',macFact2Text:'Minimum system version.',macFact3Title:'Modular interface',macFact3Text:'Resize and compose the workspace around the job.',directDownload:'Direct download',directDownloadText:'Distribution outside the App Store will be enabled for launch.',
      pricingKicker:'Pricing',pricingTitle:'The full BreakOut workflow.',pricingIntro:'Payments are not connected yet. The purchase controls are in place and will become active when sales launch.',sixMonths:'6 months',oneYear:'1 year',comingSoon:'Coming soon',priceIncludes:'Access to BreakOut functionality for the paid term.',chooseSix:'Choose 6 months',chooseYear:'Choose 1 year',
      privacyKicker:'Trust and privacy',privacyTitle:'Clear rules before the first purchase.',privacyText:'The current site has no advertising trackers and does not process payment-card data. The policy will be updated before accounts and payments are enabled.',privacyLink:'Privacy policy →',termsLink:'Terms of use →',ctaEyebrow:'BreakOut for Mac',ctaTitle:'Analysis does not start after the match. It starts when the event happens.',contactSupport:'Contact support',
      modalTitle:'This function is not available yet',modalBody:'Public download, sign-in and payments will be enabled later.',modalDownload:'Public BreakOut download is not open yet.',modalAccount:'BreakOut account sign-in will be available later.',modalPayment:'Payments are not connected yet. Nothing will be charged.',close:'Close',demoToastExport:'In the app, this opens export for the selected event.',demoToastComposer:'In the app, the event can be added to Composer.',demoToastShare:'In the app, this opens the system Share menu.',demoToastDetails:'In the app, this opens the event card.',demoToastMove:'Hold ⌘ and drag the marker up or down.',
      backHome:'← Home',supportTitle:'Support',supportIntro:'Help with BreakOut for macOS, installation, access and product questions.',supportEmailTitle:'Email support',supportEmailCopy:'For technical questions, product feedback or access issues.',supportEmailButton:'Send email',supportAccessTitle:'Download and access',supportAccessCopy:'Public download and account access will open for the commercial BreakOut launch.',supportAccessButton:'View pricing',supportBeforeTitle:'When reporting a technical issue',supportBeforeCopy:'Please include your BreakOut version, macOS version, what you were doing and the exact error message. Add a screenshot when the problem is visual.',supportPaymentsTitle:'Payments and subscriptions',supportPaymentsCopy:'After sales open, your BreakOut account will show access and subscription information.',
      privacyPageTitle:'Privacy Policy',privacyPageIntro:'How the BreakOut website handles information before accounts and payments are enabled.',version:'Version: 19 August 2026',privacyNotice:'The current site has no account forms or payment processing. It also has no advertising pixels or marketing analytics.',privacy1Title:'1. Information on the current site',privacy1Copy:'BreakOut does not collect account credentials, payment-card details, match video or project files through this website. If you email support, the information you send is used to answer your request.',privacy2Title:'2. Accounts and access',privacy2Copy:'When customer accounts are introduced, this policy will be updated to explain what information is required and why.',privacy3Title:'3. Payments',privacy3Copy:'Payment-card details will be handled by the selected payment provider rather than stored by the BreakOut website.',privacy4Title:'4. Video and projects',privacy4Copy:'BreakOut is designed for professional video work on Mac. Any future network features, if introduced, will be described before they are enabled.',privacy5Title:'5. Contact',privacy5Copy:'Privacy questions can be sent to',
      termsPageTitle:'Terms of Use',termsPageIntro:'Basic terms for using the BreakOut website before public sales begin.',termsNotice:'Purchases cannot currently be completed on this website. Prices on the home page are planned launch prices.',terms1Title:'1. Website',terms1Copy:'This website presents BreakOut and its Mac application. Until download, sign-in and purchasing open, those controls show an availability notice.',terms2Title:'2. Software access',terms2Copy:'When sales open, using BreakOut will require valid paid access.',terms3Title:'3. Intellectual property',terms3Copy:'BreakOut, its visual identity, software and original materials are protected by applicable intellectual-property rules. Receiving a copy of the application does not grant redistribution rights.',terms4Title:'4. Access and payments',terms4Copy:'Access duration, renewal, cancellation, refunds, taxes and payment conditions will be shown clearly before payment.',terms5Title:'5. Contact',terms5Copy:'Questions about these terms can be sent to'
    }
  };
  let lang=localStorage.getItem('breakout-lang')||(navigator.language?.toLowerCase().startsWith('ru')?'ru':'en');if(!tr[lang])lang='ru';const t=k=>tr[lang][k]||null;
  let theme=document.documentElement.dataset.theme||localStorage.getItem('breakout-theme')||'dark';if(!['light','dark'].includes(theme))theme='dark';
  function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function applyTheme(){document.documentElement.dataset.theme=theme;document.querySelectorAll('[data-theme-option]').forEach(b=>{const active=b.dataset.themeOption===theme;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));const label=t(b.dataset.themeOption==='light'?'lightTheme':'darkTheme')||(b.dataset.themeOption==='light'?'Light theme':'Dark theme');b.title=label;b.setAttribute('aria-label',label)});const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=theme==='light'?'#f5f8f2':'#070907'}
  function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const v=t(el.dataset.i18n);if(v!=null)el.textContent=v});document.querySelectorAll('[data-i18n-lines]').forEach(el=>{const v=t(el.dataset.i18nLines);if(v!=null)el.innerHTML=v.split('\n').map(x=>`<span>${esc(x)}</span>`).join('<br>')});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));const page=document.body.dataset.page||'home';const titles={home:lang==='ru'?'BreakOut — спортивный видеоанализ для Mac':'BreakOut — Sports Video Analysis for Mac',support:`${t('supportTitle')||'Support'} — BreakOut`,privacy:`${t('privacyPageTitle')||'Privacy'} — BreakOut`,terms:`${t('termsPageTitle')||'Terms'} — BreakOut`};document.title=titles[page]||'BreakOut';document.querySelectorAll('.slide-zoom').forEach(b=>{const label=t('zoomScreenshot')||'Enlarge screenshot';b.title=label;b.setAttribute('aria-label',label)});document.querySelectorAll('[data-lightbox-close]').forEach(b=>b.setAttribute('aria-label',t('closeScreenshot')||'Close'));applyTheme();updateContextStarLabel()}
  document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.setItem('breakout-lang',lang);applyLanguage()}));
  document.querySelectorAll('[data-theme-option]').forEach(b=>b.addEventListener('click',()=>{theme=b.dataset.themeOption;localStorage.setItem('breakout-theme',theme);applyTheme()}));
  const menuBtn=document.querySelector('.menu-btn'),mobileNav=document.querySelector('.mobile-nav');menuBtn?.addEventListener('click',()=>{const open=mobileNav?.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(!!open))});mobileNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>mobileNav.classList.remove('open')));
  const modal=document.querySelector('.modal-backdrop'),modalCopy=document.querySelector('[data-modal-copy]');function openModal(k){if(modalCopy)modalCopy.textContent=t(k)||t('modalBody')||'';modal?.classList.add('open');document.body.style.overflow='hidden'}function closeModal(){modal?.classList.remove('open');document.body.style.overflow=''}document.querySelectorAll('[data-modal-close]').forEach(b=>b.addEventListener('click',closeModal));modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeLightbox();hideContext()}});function goOrModal(url,k){if(url)location.href=url;else openModal(k)}document.querySelectorAll('[data-action="download"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();goOrModal(config.downloadURL,'modalDownload')}));document.querySelectorAll('[data-action="signin"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();goOrModal(config.signInURL,'modalAccount')}));document.querySelectorAll('[data-action="buy-six"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();goOrModal(config.purchaseSixMonthsURL,'modalPayment')}));document.querySelectorAll('[data-action="buy-year"]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();goOrModal(config.purchaseAnnualURL,'modalPayment')}));document.querySelectorAll('[data-support-email]').forEach(el=>{const email=config.supportEmail||'';if(email){el.href=`mailto:${email}`;if(el.hasAttribute('data-email-text'))el.textContent=email}});

  // Carousel
  const track=document.querySelector('.showcase-track'),slides=track?[...track.querySelectorAll('.showcase-slide')]:[],prev=document.querySelector('.carousel-arrow.prev'),next=document.querySelector('.carousel-arrow.next'),dots=document.querySelector('.carousel-dots');let active=0,scrollTimer;function centerSlide(i,behavior='smooth'){if(!track||!slides.length)return;active=(i+slides.length)%slides.length;const s=slides[active];track.scrollTo({left:s.offsetLeft-(track.clientWidth-s.clientWidth)/2,behavior});updateCarousel()}function updateCarousel(){slides.forEach((s,i)=>s.classList.toggle('active',i===active));dots?.querySelectorAll('button').forEach((d,i)=>d.classList.toggle('active',i===active))}if(slides.length&&dots){slides.forEach((_,i)=>{const d=document.createElement('button');d.type='button';d.setAttribute('aria-label',String(i+1));d.addEventListener('click',()=>centerSlide(i));dots.appendChild(d)});prev?.addEventListener('click',()=>centerSlide(active-1));next?.addEventListener('click',()=>centerSlide(active+1));track.addEventListener('scroll',()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{const c=track.scrollLeft+track.clientWidth/2;let best=0,dist=Infinity;slides.forEach((s,i)=>{const d=Math.abs(s.offsetLeft+s.clientWidth/2-c);if(d<dist){dist=d;best=i}});active=best;updateCarousel()},70)},{passive:true});track.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();centerSlide(active-1)}if(e.key==='ArrowRight'){e.preventDefault();centerSlide(active+1)}});requestAnimationFrame(()=>centerSlide(0,'auto'));window.addEventListener('resize',()=>centerSlide(active,'auto'))}
  // Screenshot lightbox — lets mobile users inspect the real UI without cropping
  const lightbox=document.querySelector('#image-lightbox'),lightboxImg=document.querySelector('#image-lightbox-img'),lightboxCaption=document.querySelector('#image-lightbox-caption');
  function openLightbox(slide){if(!lightbox||!lightboxImg||!slide)return;const img=slide.querySelector('.slide-image img');if(!img)return;lightboxImg.src=img.currentSrc||img.src;lightboxImg.alt=img.alt||'';if(lightboxCaption)lightboxCaption.textContent=slide.querySelector('.slide-caption h3')?.textContent||'';lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
  function closeLightbox(){if(!lightbox)return;lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');if(!modal?.classList.contains('open'))document.body.style.overflow=''}
  slides.forEach(slide=>{const frame=slide.querySelector('.slide-image');if(!frame)return;const zoom=document.createElement('button');zoom.type='button';zoom.className='slide-zoom';zoom.textContent='↗';zoom.setAttribute('aria-label',t('zoomScreenshot')||'Enlarge screenshot');zoom.title=t('zoomScreenshot')||'Enlarge screenshot';zoom.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openLightbox(slide)});frame.appendChild(zoom);frame.addEventListener('dblclick',()=>openLightbox(slide))});
  document.querySelectorAll('[data-lightbox-close]').forEach(b=>b.addEventListener('click',closeLightbox));lightbox?.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});

  const workflow=document.querySelector('#workflow-path');if(workflow&&'IntersectionObserver'in window)new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.25}).observe(workflow);

  // Demo
  let contextMarker=null;
  const demo=document.querySelector('#breakout-demo');if(demo){
    const timeline=document.querySelector('#timeline-demo'),tracksEl=document.querySelector('#timeline-tracks'),playhead=document.querySelector('#demo-playhead'),clock=document.querySelector('#demo-clock'),captureTime=document.querySelector('#capture-time'),captureFill=document.querySelector('#capture-progress-fill'),replayFill=document.querySelector('#replay-progress-fill'),replayEmpty=document.querySelector('#replay-empty'),replayInfo=document.querySelector('#replay-info'),replayName=document.querySelector('#replay-name'),replayTime=document.querySelector('#replay-time'),replayStage=document.querySelector('#replay-stage'),codingButtons=[...document.querySelectorAll('.coding-btn')],context=document.querySelector('#demo-context'),toast=document.querySelector('#demo-toast');
    let demoSeconds=23*60+54,windowStart=23*60+30,windowDuration=40,lastTick=performance.now(),selectedMarker=null,replayTimer=null,toastTimer=null;const running=new Map();
    function format(sec){sec=Math.max(0,Math.round(sec));return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
    function currentPct(){return Math.max(4,Math.min(96,((demoSeconds-windowStart)/windowDuration)*100))}
    function updateClock(){const p=currentPct();clock.textContent=format(demoSeconds);captureTime.textContent=`00:${format(demoSeconds)} / 01:33:17`;captureFill.style.width=`${Math.min(100,26+p*.12)}%`;playhead.style.left=`calc(72px + (100% - 72px) * ${p/100})`;running.forEach(({marker,startPct})=>{const end=currentPct();setMarkerGeometry(marker,startPct,Math.max(2,end-startPct))})}
    function tick(now){const dt=(now-lastTick)/1000;lastTick=now;demoSeconds+=dt*.42;if(demoSeconds>windowStart+windowDuration-1)demoSeconds=windowStart+4;updateClock();requestAnimationFrame(tick)}requestAnimationFrame(tick);
    function trackSurface(name){return document.querySelector(`.demo-track[data-track="${CSS.escape(name)}"] .track-surface`)}
    function setMarkerGeometry(marker,left,width){marker.dataset.left=String(Math.max(0,Math.min(98,left)));marker.dataset.width=String(Math.max(1.5,Math.min(100-Number(marker.dataset.left),width)));marker.style.left=`${marker.dataset.left}%`;marker.style.width=`${marker.dataset.width}%`}
    function createMarker({name,track,color,left=currentPct()-7,width=14,runningMode=false}){const surface=trackSurface(track)||trackSurface('chance');const marker=document.createElement('div');marker.className='demo-marker'+(runningMode?' running':'');marker.dataset.name=name;marker.dataset.track=track;marker.dataset.color=color;marker.style.background=color;marker.innerHTML=`<span class="marker-title">${esc(name)}</span><i class="marker-handle left"></i><i class="marker-handle right"></i>`;setMarkerGeometry(marker,left,width);surface.appendChild(marker);wireMarker(marker);selectMarker(marker,true);return marker}
    function selectMarker(marker,play=false){document.querySelectorAll('.demo-marker.selected').forEach(m=>m.classList.remove('selected'));selectedMarker=marker;if(!marker)return;marker.classList.add('selected');if(play)playReplay(marker)}
    function playReplay(marker){replayEmpty.style.display='none';replayInfo.classList.add('visible');replayName.textContent=marker.dataset.name;replayTime.textContent=`00:${format(windowStart+(Number(marker.dataset.left)+Number(marker.dataset.width)/2)/100*windowDuration)}`;replayInfo.querySelector('.replay-event-color').style.background=marker.dataset.color;replayStage.querySelector('img').animate([{transform:'scale(1.015)'},{transform:'scale(1.05)'},{transform:'scale(1.015)'}],{duration:2600,easing:'linear'});clearInterval(replayTimer);let p=0;replayFill.style.width='0%';replayTimer=setInterval(()=>{p+=4;replayFill.style.width=`${p}%`;if(p>=100)clearInterval(replayTimer)},100)}
    function wireMarker(marker){let drag=null;marker.addEventListener('pointerdown',e=>{if(e.button!==0)return;hideContext();const handle=e.target.closest('.marker-handle');const surface=marker.parentElement;const rect=surface.getBoundingClientRect();if(handle){e.preventDefault();e.stopPropagation();drag={type:handle.classList.contains('left')?'left':'right',startX:e.clientX,left:Number(marker.dataset.left),width:Number(marker.dataset.width),rect};marker.setPointerCapture(e.pointerId);selectMarker(marker,false)}else if(e.metaKey||e.ctrlKey){e.preventDefault();drag={type:'moveTrack',startY:e.clientY};marker.setPointerCapture(e.pointerId);selectMarker(marker,false)}else selectMarker(marker,true)});marker.addEventListener('pointermove',e=>{if(!drag)return;if(drag.type==='left'||drag.type==='right'){const delta=(e.clientX-drag.startX)/drag.rect.width*100;if(drag.type==='left'){const nl=Math.max(0,Math.min(drag.left+drag.width-2,drag.left+delta));setMarkerGeometry(marker,nl,drag.width+(drag.left-nl))}else setMarkerGeometry(marker,drag.left,Math.max(2,drag.width+delta))}});marker.addEventListener('pointerup',e=>{if(!drag)return;if(drag.type==='moveTrack'){const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.demo-track');if(el){const target=el.querySelector('.track-surface');target.appendChild(marker);marker.dataset.track=el.dataset.track}}drag=null});marker.addEventListener('contextmenu',e=>{e.preventDefault();selectMarker(marker,false);showContext(marker,e.clientX,e.clientY)})}
    codingButtons.forEach(btn=>btn.addEventListener('click',()=>{const mode=btn.dataset.mode,name=btn.dataset.name,trackName=btn.dataset.track,color=btn.dataset.color;if(mode==='pressAndRelease'){if(running.has(btn)){const data=running.get(btn);data.marker.classList.remove('running');running.delete(btn);btn.classList.remove('active');selectMarker(data.marker,true)}else{const start=currentPct();const marker=createMarker({name,track:trackName,color,left:start,width:2,runningMode:true});running.set(btn,{marker,startPct:start});btn.classList.add('active')}}else createMarker({name,track:trackName,color,left:currentPct()-8,width:16})}));
    // Seed a few realistic markers
    createMarker({name:'GOAL +',track:'goal',color:'#69dc35',left:14,width:9});createMarker({name:'OZ',track:'oz',color:'#2ebd34',left:31,width:18});createMarker({name:'Chance',track:'chance',color:'#d36adf',left:54,width:12});selectMarker(null,false);replayEmpty.style.display='grid';replayInfo.classList.remove('visible');
    function showContext(marker,x,y){contextMarker=marker;updateContextStarLabel();context.classList.add('open');context.setAttribute('aria-hidden','false');const w=220,h=250;context.style.left=`${Math.min(x,innerWidth-w-10)}px`;context.style.top=`${Math.min(y,innerHeight-h-10)}px`}
    function hideContext(){context?.classList.remove('open');context?.setAttribute('aria-hidden','true');contextMarker=null}window.addEventListener('pointerdown',e=>{if(context?.classList.contains('open')&&!context.contains(e.target))hideContext()});
    function showToast(key){if(!toast)return;toast.textContent=t(key)||key;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2300)}
    context?.addEventListener('click',e=>{const b=e.target.closest('button[data-menu]');if(!b||!contextMarker)return;const action=b.dataset.menu;if(action==='delete'){contextMarker.remove();selectedMarker=null;replayInfo.classList.remove('visible');replayEmpty.style.display='grid'}else if(action==='star'){contextMarker.classList.toggle('starred')}else if(action==='export')showToast('demoToastExport');else if(action==='composer')showToast('demoToastComposer');else if(action==='share')showToast('demoToastShare');else if(action==='details')showToast('demoToastDetails');hideContext()});
    function splitDrag(el,axis){el?.addEventListener('pointerdown',e=>{if(innerWidth<760)return;e.preventDefault();el.classList.add('dragging');el.setPointerCapture(e.pointerId);const grid=demo.querySelector('.demo-grid'),r=grid.getBoundingClientRect();const move=ev=>{if(axis==='x'){const pct=(ev.clientX-r.left)/r.width*100;demo.style.setProperty('--split-x',`${Math.max(58,Math.min(82,pct))}%`)}else{const pct=(ev.clientY-r.top)/r.height*100;demo.style.setProperty('--split-y',`${Math.max(42,Math.min(72,pct))}%`)}};const up=()=>{el.classList.remove('dragging');el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)})}splitDrag(document.querySelector('#splitter-x'),'x');splitDrag(document.querySelector('#splitter-y'),'y');
  }
  function updateContextStarLabel(){const btn=document.querySelector('[data-menu="star"]');if(!btn)return;const starred=contextMarker?.classList.contains('starred');btn.textContent=t(starred?'ctxUnstar':'ctxStar')||(starred?'Убрать звёздочку':'Поставить звёздочку')}
  applyLanguage();
})();
